packages:
  - frontend
  - portal-cliente-api

nodeLinker: isolated
strictPeerDependencies: false

allowBuilds:
  '@nestjs/core': true
  '@prisma/client': true
  '@prisma/engines': true
  bcrypt: true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
  core-js: false
  '@scarf/scarf': false
