FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

COPY prisma ./prisma/

# Configurar npm para ignorar certificados SSL
ENV NODE_TLS_REJECT_UNAUTHORIZED=0
ENV NPM_CONFIG_STRICT_SSL=false

RUN npm install

# Gerar AMBOS os clientes Prisma usando npx
RUN npx prisma generate --schema=prisma/postgres/schema.prisma
RUN npx prisma generate --schema=prisma/sqlserver/schema.prisma

COPY . .

EXPOSE 5000

CMD ["npm", "run", "dev"]