-- CreateTable
CREATE TABLE "faturamento" (
    "id" SERIAL NOT NULL,
    "cod_cli" VARCHAR(50) NOT NULL,
    "n_fatura" VARCHAR(50) NOT NULL,
    "cliente" VARCHAR(255) NOT NULL,
    "endereco" VARCHAR(255),
    "bairro" VARCHAR(100),
    "cidade" VARCHAR(100),
    "uf" VARCHAR(2),
    "cep" VARCHAR(10),
    "cgc" VARCHAR(20),
    "insc_esta" VARCHAR(50),
    "insc_munic" VARCHAR(50),
    "rps" VARCHAR(50),
    "tp_nota" VARCHAR(20),
    "vl_extenso" VARCHAR(255),
    "valor_fatura" DECIMAL(10,2) NOT NULL,
    "valor_servicos" DECIMAL(10,2) NOT NULL,
    "dt_fatura" DATE NOT NULL,
    "dt_vencimento" DATE NOT NULL,
    "dt_entrada" DATE,
    "iss_cobrar" VARCHAR(5),
    "iss_valor" DECIMAL(10,2),
    "iss_percentual" DECIMAL(5,2),
    "iii_valor" DECIMAL(10,2),
    "tributacao_msg" TEXT,
    "observacao" TEXT,
    "modalidade" VARCHAR(50),
    "despachante" VARCHAR(100),
    "valor_cif" DECIMAL(10,2),
    "n_da" VARCHAR(50),
    "n_di" VARCHAR(50),
    "n_lote" VARCHAR(50),
    "n_conhecimento" VARCHAR(50),
    "n_documento" VARCHAR(50),
    "tx_dolar" DECIMAL(10,4),
    "nr_periodo_i" INTEGER,
    "nr_periodo_f" INTEGER,
    "dt_periodo_f" DATE,
    "qt_volumes" INTEGER,
    "peso_bruto" DECIMAL(10,2),
    "m3" DECIMAL(10,2),
    "quantidade" INTEGER,
    "servico_id" VARCHAR(50),
    "servico" VARCHAR(100),
    "valor" DECIMAL(10,2),
    "modalidade_txt" VARCHAR(100),

    CONSTRAINT "faturamento_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "faturamento_n_fatura_key" ON "faturamento"("n_fatura");
