api:
  dashboard: true
  insecure: true # Disponível em :8080

entryPoints:
  web:
    address: ":80"

providers:
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true
  # docker:
  #   exposedByDefault: false

log:
  level: INFO
